import "./globals.css";

import type { Metadata } from "next";
import { Short_Stack } from "next/font/google";

const shortStack = Short_Stack({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pattern Saver",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light" className={`antialiased`}>
      <body className={`${shortStack.className}`}>{children}</body>
    </html>
  );
}
